# https://github.com/realm/SwiftLint#configuration

disabled_rules:
    - function_parameter_count
    - cyclomatic_complexity
    - file_length
opt_in_rules:
    - force_unwrapping

excluded:
    - Pods

